credentials:
  usernames:
    admin:
      name: Administrador
      password: giuberttimarquez # To be replaced with hashed password
    486asfaswfae:
      name: Rebecca Briggs
      password: gasgagwsgjtjd
    agasgmhgaghr:
      name: 4619asfuqb
      password: 4868asfasfag4as4gq
    gagegoasngpa:
      name: 4619asfuqb
      password: 4868g4ajfgjgfs4gq
    asgneiganga:
      name: 4619asfuqb
      password: 4868g4ahdh4rs4gq
    sdgk0qwofas:
      name: 4619asfuqb
      password: 4868g4nstensas4gq
    asfiniwfniao:
      name: 4619asfuqb
      password: 4868g4anewtwetns4gq
    lsdghmpshsdh:
      name: 4619asfuqb
      password: 4868g4aa4ky4es4gq
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com