credentials:
  usernames:
    admin:
      name: Administrador
      password: giuberttimarquez # To be replaced with hashed password
    486asfaswfae:
      name: Rebecca Briggs
      password: gasgagwsgjtjd
    4619asfuqb:
      name: 4619asfuqb
      password: 4868g4as4gq
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com